version: '1'

services:
  db:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: 'Barbershop'
      MYSQL_USER: 'andre'
      MYSQL_PASSWORD: 'andre'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - '3306:3306'
    volumes:
      - barbershop_db_volume:/var/lib/mysql

volumes:
  barbershop_db_volume: